### PR TITLE
Switched Fork on Github to Footer and indigoBox Link to Header

### LINKED ISSUE #6: Alteration of Header and footer
The header and footer should switch information, given that forking isitfresh on GitHub is not as important as brand recognition for IndigoBox Studios. See below.

switch mockup

### PR DESCRIPTION
**Pull request by vkoves**
Switched Fork on Github to footer and indigoBox link to header. Also made indigoBox text all white for accessibility, and made links underlined for clarity.

Resolves #6 

Screenshots:

image

image

### CODE REVIEW

**Review by rjaltman — COMMENTED** [review]
I think the changes look good, but I sort of want to avoid underlines as much as we can if we usually don't do underlined links across IndigoBox. Personally, if we can come up with some other way of making it clearer that's a link, it would be preferable - but I honestly am not sure there _is_ a better way right now. 

Reviewing this comment again, it might just be the proximity of the underline that throws me off - or that I'm not used to seeing underlines on links if using a mobile app unless it is in an article.

**Comment by vkoves** [comment]
@rjaltman - I agree with you, but I think this is the simplest solution for now. I'd suggest revising this later unless you think it's really atrocious

**Comment by SorenSpicknall** [comment]
@rjaltman, do you think it's acceptable for the moment? I do believe the other visual changes warrant the slight clunkiness of the underline.

**Comment by rjaltman** [comment]
@AcademyInPeril, I think we can go with this for now - we can review this in full later, but focusing on the brand is the main goal here. I will say the font change is a little awkward, and the wordmark is now out of date, but otherwise I think this works.

**Comment by vkoves** [comment]
@rjaltman  - as the reviewer, you need to take a hard stance on if this is needs changes or is approved. I'd like one or other at this point with this pull request's age.

**Comment by vkoves** [comment]
I am merging this now, since it's stale but good.

**Pull request merged**
